---
# Français par défaut, fuseau Burkina Faso ; l'utilisateur peut changer
region: "Africa"
zone: "Ouagadougou"
geoip:
  style: "json"
  url: "https://geoip.kde.org/v1/calamares"
  selector: ""
localeGenPath: "/etc/locale.gen"
