---
backend: apt
update_db: false
skip_if_no_internet: true
operations:
  - remove:
      - calamares
      - calamares-settings-ubuntu-common
      - live-boot
      - live-config
      - live-config-systemd
      - live-tools
      - casper
      - lupin-casper
      - user-setup
      - localechooser-data
