---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512M
efiSystemPartitionName: "EFI"
userSwapChoices:
  - none
  - small
  - file
swapPartitionName: "swap"
drawNestedPartitions: false
alwaysShowPartitionLabels: true
allowManualPartitioning: true
initialPartitioningChoice: erase
initialSwapChoice: none
defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4", "btrfs", "xfs"]
# Chiffrement du disque proposé (LUKS) : case à cocher dans l'écran "Effacer le disque"
enableLuksAutomatedPartitioning: true
luksGeneration: luks2
requiredPartitionTableType:
  - gpt
  - msdos
