---
defaultGroups:
  - name: users
    must_exist: true
  - adm
  - cdrom
  - dip
  - lpadmin
  - plugdev
  - sambashare
  - sudo
  - docker
  - kvm
  - dialout
autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: false
doReusePassword: true
passwordRequirements:
  minLength: 6
  maxLength: -1
allowWeakPasswords: true
allowWeakPasswordsDefault: false
userShell: /bin/bash
setHostname: EtcFile
writeHostsFile: true
forbidden_names: [ root, nos, naabiga ]
