---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: true
showDonateUrl: false
requirements:
  requiredStorage: 25.0
  requiredRam: 2.0
  internetCheckUrl: https://github.com
  check:
    - storage
    - ram
    - power
    - internet
    - root
  required:
    - storage
    - ram
    - root
