# Naabiga OS : écran de connexion (Slick Greeter)
[Greeter]
background=/usr/share/backgrounds/naabiga/naabiga-login.svg
background-color=#111111
logo=/usr/share/nos/branding/logo.png
theme-name=Yaru-red-dark
icon-theme-name=Papirus-Dark
font-name=Inter 11
draw-user-backgrounds=false
draw-grid=false
show-hostname=true
clock-format=%H:%M
