name: nos_center
description: N-OS Center — centre logiciel graphique de Naabiga OS (Flutter Desktop, Linux).
publish_to: "none"
version: 1.0.0-alpha.1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
